Events/urls.py
from django.urls import path
from django.conf.urls import url
from Event_and_creator import urls

from django.contrib import admin
from django.urls import include
from . import views

urlpatterns = [
    url(r'^event_and_creator/', include('Event_and_creator.urls')),  # http://127.0.0.1:8000/event_and_creator/main
    url(r'^people/', include('People.urls')),  # http://127.0.0.1:8000/people/main
    url(r'^transfer/', include('Flights.urls')),  # http://127.0.0.1:8000/transfer/main
    url(r'^logistics/', include('Logistics.urls')),  # http://127.0.0.1:8000/logistics/main
    url(r'^money/', include('Money.urls')),  # http://127.0.0.1:8000/money/main
    url(r'^rooms/', include('Rooms.urls')),  # http://127.0.0.1:8000/rooms/main
    url(r'^storage/', include('Storage.urls')),  # http://127.0.0.1:8000/storage/main
    url(r'^timetable/', include('Timetable.urls')),  # http://127.0.0.1:8000/timetable/main
    path('admin/', admin.site.urls),
    url(r'^main$', views.MainView.as_view()),  # http://127.0.0.1:8000/main
    url(r'^secret$', views.SecretView.as_view()),  # http://127.0.0.1:8000/secret
]

Flights/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views

app_name = 'Flights'

urlpatterns = [
    url(r'^waybill$',  views.WaybillViewTestIndex, name='waybill'),# http://127.0.0.1:8000/transfer/waybill
    #path('waybill/create_ajax/', views.Waybill_ajax_view, name='waybill_create_ajax'),
    url(r'^waybill/create_ajax/$', views.Waybill_ajax_view, name='waybill_create_ajax')


]

Money/urls.py
from django.conf.urls import url
from . import views

app_name = 'plat_income'

urlpatterns = [
    url(r'^main$', views.MainView.as_view()),  # http://127.0.0.1:8000/Money/main
]

templates/Main_page.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block css %}
        <link href="https://fonts.googleapis.com/css2?family=Vollkorn:ital,wght@0,700;0,800;1,700&display=swap"
              rel="stylesheet">
        <title>Main page</title>
    {% endblock css %}
</head>
<body>
{% block body %}
    {% load static %}
    <div id="slider" class="carousel slide carousel-fade" data-ride="carousel" style="padding-bottom: 10px">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="https://picsum.photos/1920/750?grayscale?random=1"
                     alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="https://picsum.photos/1920/750?grayscale?random=2"
                     alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="https://picsum.photos/1920/750?grayscale?random=3"
                     alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#slider" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#slider" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="container-fluid mt-5">

    </div>
    <div class="container-fluid mt-5">
        <div class="container p-5">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12" style="padding-bottom: 3rem">
                    <div class="card" style="padding-bottom: 3rem">

                        <!-- Card image -->
                        <img class="card-img-top" src="https://picsum.photos/1920/1280?grayscale?random=4"
                             alt="Card image cap">

                        <!-- Card content -->
                        <div class="card-body">

                            <!-- Title -->
                            <h4 class="card-title"><a>Card title</a></h4>
                            <!-- Text -->
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk
                                of
                                the
                                card's
                                content.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12" style="padding-bottom: 3rem">
                    <div class="card" style="padding-bottom: 3rem">

                        <!-- Card image -->
                        <img class="card-img-top" src="https://picsum.photos/1920/1280?grayscale?random=5"
                             alt="Card image cap">

                        <!-- Card content -->
                        <div class="card-body">

                            <!-- Title -->
                            <h4 class="card-title"><a>Card title</a></h4>
                            <!-- Text -->
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk
                                of
                                the
                                card's
                                content.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12" style="padding-bottom: 3rem">
                    <div class="card" style="padding-bottom: 3rem">

                        <!-- Card image -->
                        <img class="card-img-top" src="https://picsum.photos/1920/1280?grayscale?random=6"
                             alt="Card image cap">

                        <!-- Card content -->
                        <div class="card-body">

                            <!-- Title -->
                            <h4 class="card-title"><a>Card title</a></h4>
                            <!-- Text -->
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk
                                of
                                the
                                card's
                                content.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer -->
    <footer class="page-footer font-small unique-color-dark pt-4">
        <!-- Footer Text -->
        <div class="container-fluid text-center text-md-left">
            <!-- Call to action -->
            <ul class="list-unstyled list-inline text-center py-2">
                <li class="list-inline-item">
                    <h5 class="mb-1">Регистрируйся бесплатно</h5>
                </li>
                <li class="list-inline-item">
                    <a href="#" class="btn blue-gradient">*тык*</a>
                </li>
            </ul>
            <!-- Grid row -->
            <div class="row">

                <!-- Grid column -->
                <div class="col-md-6 mt-md-0 mt-3 text-center ">

                    <!-- Content -->
                    <h5 class="text-uppercase text-muted text-center font-weight-bold">Давидище Каграманёвски</h5>
                    <a href="https://vk.com/armageddonreloaded">
                        <div class="view overlay d-flex justify-content-around rounded" style="width: 200px; margin-left: auto;
    margin-right: auto">
                            <img src="{% static 'images/Main_page/Dovid.jpg' %}" class="img-fluid rounded  hoverable"
                                 alt="Dovid">
                            <div class="mask flex-center waves-effect waves-light rgba-red-light">
                                <p class="white-text">VK</p>
                            </div>
                        </div>
                    </a>
                </div>
                <!-- Grid column -->

                <hr class="clearfix w-100 d-md-none pb-3">

                <!-- Grid column -->
                <div class="col-md-6 mb-md-0 mb-3 text-center">

                    <!-- Content -->
                    <h5 class="text-uppercase text-muted text-center font-weight-bold">Дмитриё Годяёвски</h5>
                    <a href="https://vk.com/noway.casper">
                        <div class="view overlay d-flex justify-content-around rounded" style="width: 200px; margin-left: auto;
    margin-right: auto">
                            <img src="{% static 'images/Main_page/Dmitrii.jpg' %}" class="img-fluid rounded  hoverable"
                                 alt="Dimitrii">
                            <div class="mask flex-center waves-effect waves-light rgba-red-light">
                                <p class="white-text">VK</p>
                            </div>
                        </div>
                    </a>
                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row -->


        </div>
        <!-- Footer Text -->

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3" style="background-color: #9cc7d5;">© 2020:
            <a href="http://127.0.0.1:8000/transfer/secret"> *Тык*</a>
        </div>
        <!-- Copyright -->

    </footer>
{% endblock %}
</body>
</html>

templates/Template for future(extends base).html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<!-- для ссылок на новые стили!-->
    {% block css %}
    {% endblock css %}
</head>
<body>
{%  block body %}
{% endblock %}
</body>
</html>
{% block javascript %}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static '/MDb/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/MDb/css/mdb.min.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Vollkorn:ital,wght@0,700;0,800;1,700&display=swap"
          rel="stylesheet">
    {% block css %}
    {% endblock css %}
    <script type="text/javascript" src="{% static 'MDb/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'MDb/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'MDb/js/mdb.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'MDb/js/popper.min.js' %}"></script>
    <title>Startpage</title>

</head>
<body>
<div class='container'>
    {% block content %}
    {% endblock content %}
</div>
<!-- jQuery first, then Tether, then Bootstrap JS. -->

{% block javascript %}
{% endblock javascript %}
<nav class="navbar navbar-expand-xl navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResposive_1"
                aria-controls="navbarResposive_1" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResposive_1">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item active">
                    <a href="#" class="nav-link">Главная</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="logout" class="nav-link">Выйти</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="register" class="nav-link">Регистрация</a>
                    </li>
                    <li class="nav-item">
                        <a href="login" class="nav-link">Вход</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a href="#" class="nav-link">Справка</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<nav class="navbar navbar-expand-xl navbar-light sticky-top" style="background-color: #9cc7d5">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResposive_2"
                aria-controls="navbarResposive_2" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResposive_2">
            <ul class="navbar-nav mx-auto">
                <!-- Вот сюда нужно поставить будет ссылки на все страницы в href=***, для каждого Li элемента !-->
                <li class="nav-item">
                    <a href="event_and_creator" class="nav-link">Мероприятие</a>
                </li>
                <li class="nav-item">
                    <a href="people" class="nav-link">Люди</a>
                </li>
                <li class="nav-item">
                    <a href="timetable" class="nav-link">Расписание</a>
                </li>
                <li class="nav-item">
                    <a href="transfer" class="nav-link">Трансфер</a>
                </li>
                <li class="nav-item">
                    <a href="rooms" class="nav-link">Размещение</a>
                </li>
                <li class="nav-item">
                    <a href="logistics" class="nav-link">Логистика</a>
                </li>
                <li class="nav-item">
                    <a href="storage" class="nav-link">Реквизит и склад</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!--div ниже нижен только для тестирования прокрутки страницы, в дальнеёшем его удалить  !-->


</div>
{% block body %}
{% endblock %}
</body>
</html>
{% block js %}
{% endblock %}

{% block style %}
{% endblock %}
<style>

    body {
        /*  background-image: url(/static/images/ache.jpg);*/
        background-color: #343a40;
        background-size: 100% 100%;
        background-repeat: no-repeat;
        background-attachment: fixed;
        min-width: 200px;
    }

    .nav-link {
        display: block;
        padding: 20px 22px;
        text-decoration: none;
        font-size: 22px;
        border-bottom: 3px solid transparent;
    }

    .nav {
        position: relative;
    }

    .nav-link:focus, .nav-link:hover {
        border-bottom: 3px solid tomato;
        text-decoration: none;
    }

    smart-scroll {
        position: fixed;
        top: 0;
        right: 0;
        left: 0;
        z-index: 1030;
    }

    .scrolled-down {
        transform: translateY(-100%);
        transition: all 0.3s ease-in-out;
    }

    .scrolled-up {
        transform: translateY(0);
        transition: all 0.3s ease-in-out;
    }
</style>
<script>
    // detect scroll top or down
    if ($('.smart-scroll').length > 0) { // check if element exists
        var last_scroll_top = 0;
        $(window).on('scroll', function () {
            scroll_top = $(this).scrollTop();
            if (scroll_top < last_scroll_top) {
                $('.smart-scroll').removeClass('scrolled-down').addClass('scrolled-up');
            } else {
                $('.smart-scroll').removeClass('scrolled-up').addClass('scrolled-down');
            }
            last_scroll_top = scroll_top;
        });
    }


</script>

templates/base_flights.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/CSS/bootstrap.min.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
          integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
       <!-- david new -->



    <title>Startpage</title>

</head>
<body>
<div class='container'>
    {% block content %}
    {% endblock content %}
</div>
<!-- jQuery first, then Tether, then Bootstrap JS. -->


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>

{% block javascript %}
{% endblock javascript %}

<nav class="navbar navbar-expand-xl navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResposive_1"
                aria-controls="navbarResposive_1" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResposive_1">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item active">
                    <a href="#" class="nav-link">Главная</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="logout" class="nav-link">Выйти</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="register" class="nav-link">Регистрация</a>
                    </li>
                    <li class="nav-item">
                        <a href="login" class="nav-link">Вход</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a href="#" class="nav-link">Справка</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<nav class="navbar navbar-expand-xl navbar-light sticky-top" style="background-color: #9cc7d5">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResposive_2"
                aria-controls="navbarResposive_2" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResposive_2">
            <ul class="navbar-nav mx-auto">
                <!-- Вот сюда нужно поставить будет ссылки на все страницы в href=***, для каждого Li элемента !-->
                <li class="nav-item">
                    <a href="event_and_creator" class="nav-link">Мероприятие</a>
                </li>
                <li class="nav-item">
                    <a href="people" class="nav-link">Люди</a>
                </li>
                <li class="nav-item">
                    <a href="timetable" class="nav-link">Расписание</a>
                </li>
                <li class="nav-item">
                    <a href="transfer" class="nav-link">Трансфер</a>
                </li>
                <li class="nav-item">
                    <a href="rooms" class="nav-link">Размещение</a>
                </li>
                <li class="nav-item">
                    <a href="logistics" class="nav-link">Логистика</a>
                </li>
                <li class="nav-item">
                    <a href="storage" class="nav-link">Реквизит и склад</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!--div ниже нижен только для тестирования прокрутки страницы, в дальнеёшем его удалить  !-->
<div style="padding-bottom: 5000px"></div>
</body>
</html>


<style>

    body {
        /*  background-image: url(/static/images/ache.jpg);*/
        background-color: #E0FFFF;
        background-size: 100% 100%;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }

    .nav-link {
        display: block;
        padding: 20px 22px;
        text-decoration: none;
        font-size: 22px;
        border-bottom: 3px solid transparent;
    }

    .nav {
        position: relative;
    }

    .nav-link:focus, .nav-link:hover {
        border-bottom: 3px solid tomato;
        text-decoration: none;
    }

    smart-scroll {
        position: fixed;
        top: 0;
        right: 0;
        left: 0;
        z-index: 1030;
    }

    .scrolled-down {
        transform: translateY(-100%);
        transition: all 0.3s ease-in-out;
    }

    .scrolled-up {
        transform: translateY(0);
        transition: all 0.3s ease-in-out;
    }
</style>
<script>
    // detect scroll top or down
    if ($('.smart-scroll').length > 0) { // check if element exists
        var last_scroll_top = 0;
        $(window).on('scroll', function () {
            scroll_top = $(this).scrollTop();
            if (scroll_top < last_scroll_top) {
                $('.smart-scroll').removeClass('scrolled-down').addClass('scrolled-up');
            } else {
                $('.smart-scroll').removeClass('scrolled-up').addClass('scrolled-down');
            }
            last_scroll_top = scroll_top;
        });
    }


</script>

templates/registration.html
{% extends "base.html" %}
{% load static %}
{% block content %}


    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <div class="page-header">
  <a href="{% url 'Event_and_creator:registration' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        <h1><a href="/">Ссыл очка на что-нибудь</a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            </div>
        </div>
    </div>


    <h1>Добавление маршрутаt</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>


{% endblock %}

templates/secret.html
<html>
<body background="http://trueimages.ru/img/30/c1/a7e23fa5.jpg">
<marquee behavior=alternate direction=left bgcolor=#ffcc00>
    РекламаРекламаРеклама
</marquee>

<table border="1" bordercolor="cc215a" width="800" align="center">

    <td bgcolor="F0E68C">
        <table border="1" bordercolor="cc215a" width="790" height="200"
               cellpadding="10">

            <th background="http://trueimages.ru/img/e3/57/94033fa5.jpg">
                <h1><font color="FF00FF" face="Monotype Corsiva"><font size=+5>
                    Центральный банк "Банк"</font>
                    <h1 align="left">
                        <font color="FFD700"><font size=+5>Почти самый честный банк, дающий кредиты под 0,5%
                            годовых"</font></font>

        </table>
        <font size=+1>
            Мы совершили революцию в совршенном банкинге!
            Благодаря разделению процентов на белые и серые, мы смогли увеличить уровень жизни людей на целых 0.01%!


            <table border="1" bordercolor="cc215a" width="790" cellpadding="10">

                <td rowspan="4" width="600" bgcolor="FFA07A">
                    <h1>Как мы начинали</h1>

                    <font face="comic sans ms"> <font color="cc215a"><font size=+2>
                        <strong>Сначала мы ввели листочки деревьев как национальную валюту</strong></font></font>
                        <p>Но потом мы поняли, что они ничем не подкреплены и заменили их золотыми монетами.</p>

                        <font face="comic sans ms"> <font color="cc215a"><font size=+2>
                            <strong>Но при чем тут банкинг, спросите вы. </strong></font></font>
                            <p> Ответ на лежит поверхности. Мы начали помогать банкам разных государств, у которых в
                                денежном обороте были устаревшие листочки, и общими усилиями разработали уникальную
                                систему кредитования.</p>

                </td>

                <td bgcolor="DAA520" align="left">
                    <h3>Услуги банка</h3>

                    <p><img src="http://trueimages.ru/img/0a/71/b3f13fa5.jpg"><a
                            href="http://trueimages.ru/img/48/9a/14223fa5.jpg">Кредитование</a></p>

                    <p><img src="http://trueimages.ru/img/0a/71/b3f13fa5.jpg"><a
                            href="http://trueimages.ru/img/48/9a/14223fa5.jpg">Ипотечное кредитование</a></p>

                    <p><img src="http://trueimages.ru/img/0a/71/b3f13fa5.jpg"><a
                            href="http://trueimages.ru/img/48/9a/14223fa5.jpg">Быстрозайм</a></p>

                    <p><img src="http://trueimages.ru/img/0a/71/b3f13fa5.jpg"><a
                            href="http://trueimages.ru/img/48/9a/14223fa5.jpg">Кредит на ковер-самолет</a></p>

            </table>
            Все права защищены. Для сотрудничества присылайте почтовых голубей на адрес г.Королев пр-кт Космонавтов д40
</table>
</body>


<marquee behavior=alternate direction=left bgcolor=#ffcc00>
    РекламаРекламаРеклама
</marquee>

templates/transfer.html
{% extends "base_flights.html" %}
{% block content %}



<div class="container">
    <div class="page-header">
       <a href="{% url 'Flights:waybill' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        <h1><a href="/">Ссылочка на что-нибудь</a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            </div>
        </div>
    </div>


    <h1>Добавление маршрута</h1>
    <form method="post" name="WaybillForm">
        {% csrf_token %}
        {{ forms.waybill_form.as_p }}

        <input id="savebutton" type="button" value="Сохранить"/>
        <input id="updatebutton" type="button" value="Обновить таблицу"/>
        <input id="generatebutton" type="button" value="Сгенерить 5 рандомных записей"/>


    </form>
    <!-- форма кнопки 'edit' -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Изменение данных</h4>
                </div>
                <form id="update_waybill" action="">
                    <div class="modal-body">


                        <label>Название маршрута</label>
                        <input class="form-control" name="edit_name" waybill_id="" id="edit_name" type="text"/>
                        <label>event_id</label>
                        <input class="form-control" name="edit_event_id" waybill_id="" id="edit_event_id"
                               type="number"/>
                    </div>
                    <div class="modal-footer">
                        <input id="edit_form_save" type="button" value="Сохранить изменения"/>
                        <input id="edit_form_close" type="button" class="close" data-dismiss="modal" aria-label="Close"
                               value="Закрыть"/>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-md-8">
        <h3>Доступные маршруты</h3>
        <table id="WaybillTable" class="table table-striped">
            <tr>
                <th>id</th>
                <th>Название</th>
                <th colspan="3">event_id</th>
            </tr>
            {% if new_data %}
            {% for waybill in new_data %}
            <tr id="waybill-{{ waybill.id }}">
                <td class="waybill_id userData" name="id">{{ waybill.id }}</td>
                <td class="waybill_name userData" name="name">{{ waybill.name }}</td>
                <td class="waybill_event_id userData" name="event_id">{{ waybill.event_id }}</td>
                <td align="center">
                    <button class="btn btn-success form-control" onClick="editUser({{waybill.id}})"
                            data-toggle="modal" data-target="#myModal">Редактировать
                    </button>
                </td>
                <td align="center">
                    <button class="btn btn-danger form-control" onClick="delete_waybill({{ waybill.id }})">
                        Удалить
                    </button>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            Маршрутов нет
            {% endif %}
        </table>
    </div>
</div>


<script type="text/javascript" src="/static/js/jquerry/jquery-3.5.1.min.js"></script>
<script src="/static/js/jquerry/jquery.autocomplete.min.js" type="text/javascript"></script>
<link type="text/css" rel="stylesheet" href="/static/CSS/jquery.autocomplete.css">
<script src="/static/js/ajax_base.js"></script>
<script src="/static/js/Flights/transfer.js"></script>
<script type="text/javascript">

    /* убрать  из дополнительной формы event_id
       сделат ьпрвоерку на уникальность названия пути
       добавить id и event_id к названию путевого маршрута, но оставить их в основной табилце
       добавить нумерацию строк
       засунуть скрипты в отедльный файл
       создать файл с функциями вьюшек
     */
</script>
{% endblock %}